const NRFX_ERROR_BASE_NUM: c_int = 0x0BAD0000;
const NRFX_ERROR_DRIVERS_BASE_NUM: c_int = NRFX_ERROR_BASE_NUM + 0x10000;

pub const NrfxError = enum(c_int) {
    NRFX_SUCCESS = NRFX_ERROR_BASE_NUM + 0,
    NRFX_ERROR_INTERNAL = NRFX_ERROR_BASE_NUM + 1,
    NRFX_ERROR_NO_MEM = NRFX_ERROR_BASE_NUM + 2,
    NRFX_ERROR_NOT_SUPPORTED = NRFX_ERROR_BASE_NUM + 3,
    NRFX_ERROR_INVALID_PARAM = NRFX_ERROR_BASE_NUM + 4,
    NRFX_ERROR_INVALID_STATE = NRFX_ERROR_BASE_NUM + 5,
    NRFX_ERROR_INVALID_LENGTH = NRFX_ERROR_BASE_NUM + 6,
    NRFX_ERROR_TIMEOUT = NRFX_ERROR_BASE_NUM + 7,
    NRFX_ERROR_FORBIDDEN = NRFX_ERROR_BASE_NUM + 8,
    NRFX_ERROR_NULL = NRFX_ERROR_BASE_NUM + 9,
    NRFX_ERROR_INVALID_ADDR = NRFX_ERROR_BASE_NUM + 10,
    NRFX_ERROR_BUSY = NRFX_ERROR_BASE_NUM + 11,
    NRFX_ERROR_ALREADY_INITIALIZED = NRFX_ERROR_BASE_NUM + 12,
    NRFX_ERROR_DRV_TWI_ERR_OVERRUN = NRFX_ERROR_DRIVERS_BASE_NUM + 0,
    NRFX_ERROR_DRV_TWI_ERR_ANACK = NRFX_ERROR_DRIVERS_BASE_NUM + 1,
    NRFX_ERROR_DRV_TWI_ERR_DNACK = NRFX_ERROR_DRIVERS_BASE_NUM + 2,
};
